import time
print("-"*40)
print(f"|{'Menu':^38}|")
print("|" + " "*38 + "|")
print(f"| {'1. Test your knowledge':<36} |")
print(f"| {'2. Revise for knowledge':<36} |")
print(f"| {'3. Give me your knowledge':<36} |")
print(f"| {'4. End our knowledge':<36} |")
print("-"*40)
choice = input("Uw keuze: ")